### ISSUE TITLE
NPM Error while creating Proxy Hosts

### ISSUE THREAD

**Issue by cramer52** [baudneo/nginx-proxy-manager#3]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - No
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**
While trying to create a proxy host the following error occurs:
``` 
ER_BAD_FIELD_ERROR: Unknown column 'openidc_allowed_users' in 'field list'
``` 
Full log (edited):

``` 
[11/14/2022] [3:04:27 PM] [Express  ] › ⚠  warning   insert into `proxy_host` (`access_list_id`, `advanced_config`, `allow_websocket_upgrade`, `block_exploits`, `caching_enabled`, `created_on`, `domain_names`, `enable_proxy_protocol`, `forward_host`, `forward_port`, `forward_scheme`, `hsts_enabled`, `hsts_subdomains`, `http2_support`, `locations`, `meta`, `modified_on`, `openidc_allowed_users`, `openidc_auth_method`, `openidc_client_id`, `openidc_client_secret`, `openidc_discovery`, `openidc_redirect_uri`, `owner_user_id`, `ssl_forced`) values (0, '', true, true, false, NOW(), '[\"adress\"]', false, 'ip', port, 'http', false, false, false, '[]', '{\"letsencrypt_email\":\"admin@example.com\",\"letsencrypt_agree\":true,\"dns_challenge\":false}', NOW(), '[]', 'client_secret_post', '', '', '', '', 1, false) - ER_BAD_FIELD_ERROR: Unknown column 'openidc_allowed_users' in 'field list'
``` 

**Nginx Proxy Manager Version**
v0.0.0 © 2022 @jc21.com

**To Reproduce**
1. Create Docker image with attached Docker compose
2. Go to: http://dockerip:81
3. Click on 'Proxy Host, Add Proxy Host & fill out and click save'
4. See error (Internal error)

**Expected behavior**
The proxy host is created without an issue. The `jc21/nginx-proxy-manager:latest` works flawless.

**Operating System**
Proxmox LXC with Ubuntu 22.04

**Additional context**
Docker-compose
``` 
version: "3"
services:
  app:
    image: 'baudneo/nginx-proxy-manager:bullseye'
    restart: unless-stopped
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
    environment:
      TZ: Europe/Berlin
      ADMIN_PANEL_LOG: "1"
      CROWDSEC_BOUNCER: "1"
      OPENRESTY_DEBUG: "0"

      CROWDSEC_LAPI: "http://Crowdsec-IP:8080/"
      CROWDSEC_KEY: "api-key"
      
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "password"
      DB_MYSQL_NAME: "npm"

    volumes:
      - /Nginx-Proxy-Manger/data:/data
      - /Nginx-Proxy-Manger/letsencrypt:/etc/letsencrypt
      - /Nginx-Proxy-Manger/crowdsec-openresty-bouncer.conf:/data/crowdsec/crowdsec-openresty-bouncer.conf
    depends_on:
      - db
  db:
    image: 'jc21/mariadb-aria:latest'
    restart: always
    container_name: npm_db
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'password'
    volumes:
      - ./data/mysql:/var/lib/mysql
``` 
crowdsec-openresty-bouncer.conf
``` 
ENABLED=true
API_URL=http://crowdsecip:8080
API_KEY=API-Key
CACHE_EXPIRATION=1
# bounce for all type of remediation that the bouncer can receive from the local API
BOUNCING_ON_TYPE=all
FALLBACK_REMEDIATION=ban
REQUEST_TIMEOUT=3000
UPDATE_FREQUENCY=10
# live or stream
MODE=live
# exclude the bouncing on those location
EXCLUDE_LOCATION=
#those apply for "ban" action
# /!\ REDIRECT_LOCATION and RET_CODE can't be used together. REDIRECT_LOCATION take priority over RET_CODE
BAN_TEMPLATE_PATH=/crowdsec/templates/ban.html
REDIRECT_LOCATION=
RET_CODE=
#those apply for "captcha" action
# ReCaptcha Secret Key
SECRET_KEY=ReCaptchaSecretkeyhere
# Recaptcha Site key
SITE_KEY=RecaptchaSitekeyhere
CAPTCHA_TEMPLATE_PATH=/crowdsec/templates/captcha.html
CAPTCHA_EXPIRATION=3600
```
