### ISSUE TITLE
Can not add proxy host

### ISSUE THREAD

**Issue by franciscopaniskaseker** [baudneo/nginx-proxy-manager#4]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
No
- Are you sure you're not using someone else's docker image?
Yes 
- Have you searched for similar issues (both open and closed)?
Yes 

**Describe the bug**
Error when I try to add proxy host. This is a fresh setup;

**Nginx Proxy Manager Version**
0.0.0

**To Reproduce**
Try to create a new proxy host just adding domain, the ip and port.

**Expected behavior**
Proxy host created.

**Screenshots**
no

**Operating System**
Ubuntu 20.05

**Additional context**
I can see this log error:

```bash
[11/27/2022] [5:27:20 PM] [Express  ] › ⚠  warning   insert into `proxy_host` (`access_list_id`, `advanced_config`, `allow_websocket_upgrade`, `block_exploits`, `caching_enabled`, `certificate_id`, `created_on`, `domain_names`, `enable_proxy_protocol`, `forward_host`, `forward_port`, `forward_scheme`, `hsts_enabled`, `hsts_subdomains`, `http2_support`, `locations`, `meta`, `modified_on`, `openidc_allowed_users`, `openidc_auth_method`, `openidc_client_id`, `openidc_client_secret`, `openidc_discovery`, `openidc_enabled`, `openidc_redirect_uri`, `openidc_restrict_users_enabled`, `owner_user_id`, `ssl_forced`) values (0, '', false, false, false, 0, datetime('now','localtime'), '["test.com"]', false, '192.168.1.175', 80, 'http', false, false, false, '[]', '{"letsencrypt_agree":false,"dns_challenge":false}', datetime('now','localtime'), '[]', 'client_secret_post', '', '', '', false, '', false, 1, false) - SQLITE_ERROR: table proxy_host has no column named openidc_enabled
```

important part:
```bash
 SQLITE_ERROR: table proxy_host has no column named openidc_enabled
```

by the way, I am not trying to use openidc. I am just adding a very simple proxy host without any extra feature.

**Comment by franciscopaniskaseker** [comment]
I tried now instead of use sqlite, use mysql.

Now the error is
```bash
data should NOT have additional properties
```

when i try to add the proxy host. I note also that a MISSING config for OIDC. Please check the image:
![Screenshot 2022-11-27 at 16 14 28](https://user-images.githubusercontent.com/8779476/204155131-e70e6e5c-a4a2-4467-917a-ded59892b3cf.png)

seems to me that in both cases OIDC is causing something.

**Comment by barto95100** [comment]
I have the same error on fresh install.... :(

**Comment by nathcoad** [comment]
I also get the same error "SQLITE_ERROR: table proxy_host has no column named openidc_allowed_users" on a fresh install when trying to create a new proxy host, using sqlite in my docker-compose.yml file.

**Comment by kstawiski** [comment]
Me too. Do we have any solution?

**Comment by WhoTheHeck** [comment]
Had the same issue. Issue #3 has the solution. Changing from `latest` to `bullseye` does the trick.

**Comment by Normanras** [comment]
I have the same error, with slightly different errors. This is my error with the `latest` tag pulled:

![Screenshot 2022-12-20 at 2 45 28 PM](https://user-images.githubusercontent.com/44226464/208753398-b09331b8-2777-4fe2-a595-63a7ae3faa93.png)

And the relevant log line:
`ER_BAD_FIELD_ERROR: Unknown column 'openidc_allowed_users' in 'field list'`

Now, I've changed the tag to `bullseye`:

It works! I'll come back here if the bullseye tag has any errors regarding creating proxy hosts and `openidc`.

**Comment by nathcoad** [comment]
I just tried again, after deleting the previously used volumes and running docker-compose up --force-recreate

Here is my docker-compose.yml file. This time I get a slightly different error but still openidc focused. The UI just says internal error, same as before.

```
version: "3"
services:
  app:
    # This image a forked version with proxy support from https://github.com/NginxProxyManager/nginx-proxy-manager/pull/1882
    image: 'baudneo/nginx-proxy-manager:bullseye'
    container_name: npm-crowdsec
    restart: unless-stopped
    ports:
      # Public HTTP Port:
      - '80:80'
      # Public HTTPS Port:
      - '443:443'
      # Admin Web Port:
      - '81:81'
    environment:
      # These are the settings to access your db
      # DB_MYSQL_HOST: "db"
      # DB_MYSQL_PORT: 3306
      # DB_MYSQL_USER: "npm"
      # DB_MYSQL_PASSWORD: "npm"
      # DB_MYSQL_NAME: "npm"
      # If you would rather use Sqlite uncomment this
      # and remove all DB_MYSQL_* lines above
      DB_SQLITE_FILE: "/data/database.sqlite"
      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'
      ADMIN_PANEL_LOG: "1"
      CROWDSEC_BOUNCER: "0"
      OPENRESTY_DEBUG: "0"
      #MODSEC_CREATE: "1"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
      - ./logs:/data/logs
    networks:
      - reverseproxy-nw

networks:
reverseproxy-nw
    reverseproxy-nw:
        external: true
```

Full log message is as follows:
```
npm-crowdsec | [12/20/2022] [9:04:44 PM] [Express  ] › ⚠  warning   insert into `proxy_host` (`access_list_id`, `advanced_config`, `allow_websocket_upgrade`, `block_exploits`, `caching_enabled`, `certificate_id`, `created_on`, `domain_names`, `enable_proxy_protocol`, `forward_host`, `forward_port`, `forward_scheme`, `hsts_enabled`, `hsts_subdomains`, `http2_support`, `locations`, `meta`, `modified_on`, `openidc_allowed_users`, `openidc_auth_method`, `openidc_client_id`, `openidc_client_secret`, `openidc_discovery`, `openidc_enabled`, `openidc_redirect_uri`, `openidc_restrict_users_enabled`, `owner_user_id`, `ssl_forced`) values (0, '', false, false, false, 0, datetime('now','localtime'), '["bw.coadcorp.com"]', false, '10.0.1.25', 9000, 'http', false, false, false, '[]', '{"letsencrypt_agree":false,"dns_challenge":false}', datetime('now','localtime'), '[]', 'client_secret_post', '', '', '', false, '', false, 1, false) - SQLITE_ERROR: table proxy_host has no column named openidc_enabled
```
