### ISSUE TITLE
I can't get it to work

### ISSUE THREAD

**Issue by a1ad** [baudneo/nginx-proxy-manager#8]
Based on this tutorial: https://experimentalnetworks.com.au/?p=449

I get the message: 2023/02/08 09:49:25 [alert] 331#331: [lua] init_by_lua:11: [Crowdsec] Initialisation done
But when I manually add my desktop IP, the block is not working.

Docker-compose:
```
# https://hub.docker.com/r/baudneo/nginx-proxy-manager
# https://www.crowdsec.net/blog/crowdsec-with-nginx-proxy-manager
version: "3"

networks:
  PROXY-LAN:
    external: true
    name: int-proxy-lan
  DMZ-LAN:
    external: true
    name: dmz-lan
  SEC-LAN:
    external: true
    name: int-sec-lan

services:
  nginx-frontend:
    container_name: nginx-frontend
    # image: 'jc21/nginx-proxy-manager:latest'
    image: 'baudneo/nginx-proxy-manager:bullseye'
    ports:
      # These ports are in format :
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    environment:
      # crowdsec config
      TZ: Europe/Brussels
      ADMIN_PANEL_LOG: "1"
      CROWDSEC_BOUNCER: "1"
      OPENRESTY_DEBUG: "0"

      CROWDSEC_LAPI: "http://nginx-crowdsec:8080/"
      CROWDSEC_KEY: "api-key"
          
      DB_MYSQL_HOST: nginx-db
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "**************"
      DB_MYSQL_NAME: "npm"
    volumes:
      - ./nginx/data:/data
      - ./nginx/letsencrypt:/etc/letsencrypt
      - ./nginx/crowdsec-openresty-bouncer.conf:/data/crowdsec/crowdsec-openresty-bouncer.conf
    depends_on:
      - nginx-db
    dns: 10.30.66.1
    networks:
      DMZ-LAN:
        ipv4_address: 10.30.66.93
        priority: 100
      PROXY-LAN:
        ipv4_address: 172.18.0.22
        priority: 200
      SEC-LAN:
        priority: 300
    restart: unless-stopped


  nginx-db:
    container_name: nginx-db
    image: 'jc21/mariadb-aria:latest'
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: '**************'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: '***********'
    volumes:
      - ./nginx/data/mysql:/var/lib/mysql
    networks:
      - PROXY-LAN

  nginx-crowdsec:
    container_name: nginx-crowdsec
    #image: crowdsecurity/crowdsec:v1.3.4
    image: crowdsecurity/crowdsec:latest
    restart: always
    ports:
      - 9089:8080
    environment:
      #this is the list of collections we want to install
      #https://hub.crowdsec.net/author/crowdsecurity/collections/nginx
      COLLECTIONS: "crowdsecurity/linux crowdsecurity/nginx-proxy-manager crowdsecurity/base-http-scenarios"
      #COLLECTIONS: "crowdsecurity/cloudflare-bouncer"
      GID: "${GID-1000}"
      TZ: Europe/Brussels
    volumes:
      - ./crowdsec/acquis.yaml:/etc/crowdsec/acquis.yaml
      - ./crowdsec/profiles.yaml:/etc/crowdsec/profiles.yaml
      - ./nginx/data/logs:/var/logs
      - crowdsec-db:/var/lib/crowdsec/data/
      - crowdsec-config:/etc/crowdsec/
    networks:
      - PROXY-LAN
      - SEC-LAN
      - default

volumes:
  logs:
  crowdsec-db:
  crowdsec-config:
```
crowdsec-openresty-bouncer.conf:

```
ENABLED=true
API_URL=http://nginx-crowdsec:8080/
API_KEY=api-key
CACHE_EXPIRATION=1
# bounce for all type of remediation that the bouncer can receive from the local API
BOUNCING_ON_TYPE=all
FALLBACK_REMEDIATION=ban
REQUEST_TIMEOUT=3000
UPDATE_FREQUENCY=10
# live or stream
MODE=live
# exclude the bouncing on those location
EXCLUDE_LOCATION=
#those apply for "ban" action
# /!\ REDIRECT_LOCATION and RET_CODE can't be used together. REDIRECT_LOCATION take priority over RET_CODE
BAN_TEMPLATE_PATH=/crowdsec/templates/ban.html
REDIRECT_LOCATION=
RET_CODE=
#those apply for "captcha" action
# ReCaptcha Secret Key
SECRET_KEY=*******
# Recaptcha Site key
SITE_KEY=**********
CAPTCHA_TEMPLATE_PATH=/crowdsec/templates/captcha.html
CAPTCHA_EXPIRATION=3600
```

acquis.yaml:

```
# https://www.reddit.com/r/selfhosted/comments/ujdzwu/how_do_i_install_crowdsec_on_my_nginx_proxy/
# https://hub.crowdsec.net/author/crowdsecurity/collections/nginx-proxy-manager
filenames:
 - /var/logs/default-host_access.log
 - /var/logs/proxy-host-*_access.log
 - /var/logs/proxy-host-*_error.log
labels:
  type: nginx-proxy-manager
```

profiles.yml

```
name: captcha_remediation
filters:
- Alert.Remediation == true && Alert.GetScope() == "Ip" && Alert.GetScenario() startsWith "crowdsecurity/http-"
decisions:
- type: captcha
  duration: 4h
on_success: break
---

name: default_ip_remediation
#debug: true
filters:
 - Alert.Remediation == true && Alert.GetScope() == "Ip"
decisions:
 - type: ban
   duration: 4h
# notifications:
#   - slack_default  # Set the webhook in /etc/crowdsec/notifications/slack.yaml before enabling this.
#   - splunk_default # Set the splunk url and token in /etc/crowdsec/notifications/splunk.yaml before enabling this.
#   - http_default   # Set the required http parameters in /etc/crowdsec/notifications/http.yaml before enabling this.
#   - email_default  # Set the required email parameters in /etc/crowdsec/notifications/email.yaml before enabling this.
on_success: break
```
Docker startup logs (passwoord: crowdsec)
https://defuse.ca/b/XSAcRiyORohgHVD4GUCsJM

The metrics are looking good:

```
Acquisition Metrics:
+----------------------------------------+------------+--------------+----------------+------------------------+
|                 Source                 | Lines read | Lines parsed | Lines unparsed | Lines poured to bucket |
+----------------------------------------+------------+--------------+----------------+------------------------+
| file:/var/logs/proxy-host-2_access.log | 33         | 33           | -              | -                      |
| file:/var/logs/proxy-host-2_error.log  | 33         | 33           | -              | -                      |
+----------------------------------------+------------+--------------+----------------+------------------------+

Parser Metrics:
+----------------------------------------------+------+--------+----------+
|                   Parsers                    | Hits | Parsed | Unparsed |
+----------------------------------------------+------+--------+----------+
| child-crowdsecurity/http-logs                | 198  | 138    | 60       |
| child-crowdsecurity/nginx-proxy-manager-logs | 132  | 66     | 66       |
| crowdsecurity/dateparse-enrich               | 66   | 66     | -        |
| crowdsecurity/geoip-enrich                   | 66   | 66     | -        |
| crowdsecurity/http-logs                      | 66   | 66     | -        |
| crowdsecurity/nginx-proxy-manager-logs       | 66   | 66     | -        |
| crowdsecurity/non-syslog                     | 66   | 66     | -        |
| crowdsecurity/whitelists                     | 66   | 66     | -        |
+----------------------------------------------+------+--------+----------+

Local Api Metrics:
+--------------------+--------+------+
|       Route        | Method | Hits |
+--------------------+--------+------+
| //v1/decisions     | GET    | 33   |
| /v1/alerts         | POST   | 1    |
| /v1/heartbeat      | GET    | 15   |
| /v1/watchers/login | POST   | 3    |
+--------------------+--------+------+

Local Api Machines Metrics:
+-----------+---------------+--------+------+
|  Machine  |     Route     | Method | Hits |
+-----------+---------------+--------+------+
| localhost | /v1/heartbeat | GET    | 15   |
| localhost | /v1/alerts    | POST   | 1    |
+-----------+---------------+--------+------+

Local Api Decisions:
+--------------------------------------------+--------+--------+-------+
|                   Reason                   | Origin | Action | Count |
+--------------------------------------------+--------+--------+-------+
| crowdsecurity/spring4shell_cve-2022-22965  | CAPI   | ban    | 1     |
| crowdsecurity/apache_log4j2_cve-2021-44228 | CAPI   | ban    | 1     |
| crowdsecurity/http-generic-bf              | CAPI   | ban    | 4     |
| crowdsecurity/http-bad-user-agent          | CAPI   | ban    | 821   |
| crowdsecurity/http-open-proxy              | CAPI   | ban    | 56    |
| crowdsecurity/http-probing                 | CAPI   | ban    | 619   |
| crowdsecurity/CVE-2022-41082               | CAPI   | ban    | 1     |
| crowdsecurity/fortinet-cve-2018-13379      | CAPI   | ban    | 6     |
| crowdsecurity/http-crawl-non_statics       | CAPI   | ban    | 141   |
| crowdsecurity/http-path-traversal-probing  | CAPI   | ban    | 34    |
| crowdsecurity/http-sensitive-files         | CAPI   | ban    | 33    |
| crowdsecurity/jira_cve-2021-26086          | CAPI   | ban    | 37    |
| crowdsecurity/ssh-bf                       | CAPI   | ban    | 3908  |
| crowdsecurity/thinkphp-cve-2018-20062      | CAPI   | ban    | 9     |
| crowdsecurity/CVE-2022-42889               | CAPI   | ban    | 1     |
| crowdsecurity/f5-big-ip-cve-2020-5902      | CAPI   | ban    | 2     |
| manual 'ban' from 'localhost'              | cscli  | ban    | 1     |
| crowdsecurity/ssh-slow-bf                  | CAPI   | ban    | 1886  |
| crowdsecurity/http-backdoors-attempts      | CAPI   | ban    | 36    |
| crowdsecurity/http-cve-2021-41773          | CAPI   | ban    | 4     |
+--------------------------------------------+--------+--------+-------+

Local Api Alerts:
+-------------------------------+-------+
|            Reason             | Count |
+-------------------------------+-------+
| manual 'ban' from 'localhost' | 9     |
+-------------------------------+-------+
```

The bouncer info:

```
------------------------------------------------------------------------------------
 Name        IP Address   Valid   Last API pull          Type   Version   Auth Type 
------------------------------------------------------------------------------------
 npm-proxy                ✔️       2023-02-05T19:17:28Z                    api-key   

```

But the block isn't happening, and I don't know how to debug this thing. Does the last API pull date need to change everytime NPM bouncers contacts the lapi? Because that is not happening. Also i am using the same API URL/KEY in the crowdsec-openresty-bouncer.conf and the docker compose file for the NPM section, why do we need to specify it on both?

Can someone point me in the right direction please?
